<?php
/**
 *
 * bot-templates 2021
 */

namespace app\models;

use yii\behaviors\TimestampBehavior;

/**
 * @property int $id
 * @property int $user_id
 * @property int $action
 * @property int $ip
 * @property int $created_at
 * @property int $updated_at
 */
class UserLog extends \yii\db\ActiveRecord
{
	const ACTION_LOGIN = 1;

	/**
	 * @return string[]
	 */
	public function behaviors()
	{
		return [TimestampBehavior::class];
	}

	/**
	 * @return string
	 */
	public static function tableName()
	{
		return "user_log";
	}

	/**
	 * @param bool $insert
	 * @return bool
	 */
	public function beforeSave($insert)
	{
		$this->ip = $_SERVER['REMOTE_ADDR'];
		return parent::beforeSave($insert); // TODO: Change the autogenerated stub
	}

}